[profile.default]

optimizer = true
optimizer_runs = 800
gas_reports = []

cache = false
auto_detect_remappings = true


[profile.core]
root = 'core'

src = 'src'
test = 'test'
libs = ['lib']

out = '../build/core'
cache_path = '../cache/core'

remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',

    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
    'solmate/=lib/solmate/src/',
    'v3-core/=lib/v3-core/'
]

[profile.periphery]
#src = 'periphery/src'
#test = 'periphery/test'
#libs = ['periphery/lib', 'core', 'core/lib']

#out = 'build/periphery'
#cache_path = 'cache/periphery'

# --------------------------------
root = 'periphery'

src = 'src'
test = 'test'
libs = ['lib']

out = '../build/core'
cache_path = '../cache/core'

allow_paths = [
    '../core'
]
# --------------------------------

remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',

    'openzeppelin-contracts/=lib/core/lib/openzeppelin-contracts/contracts/',
    'solmate/=lib/core/lib/solmate/src/',
    'v3-core/=lib/core/lib/v3-core/',

    '@aloelabs/aloe-ii/core/=lib/core/src/'
]
