name: ci-test

run-name: Testing contracts

env:
  RPC_URL_MAINNET: ${{ secrets.RPC_URL_MAINNET }}
  RPC_URL_GOERLI: ${{ secrets.RPC_URL_GOERLI }}
  RPC_URL_OPTIMISM: ${{ secrets.RPC_URL_OPTIMISM }}
  RPC_URL_ARBITRUM: ${{ secrets.RPC_URL_ARBITRUM }}

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  # lint:
  #   runs-on: "ubuntu-latest"
  #   steps:
  #     - name: "Check out the repo"
  #       uses: "actions/checkout@v3"
  #       with:
  #         submodules: "recursive"

  #     - name: "Install Foundry"
  #       uses: "foundry-rs/foundry-toolchain@v1"

  #     - name: "Install Node.js"
  #       uses: "actions/setup-node@v3"
  #       with:
  #         cache: "yarn"
  #         node-version: "lts/*"

  #     - name: "Install the Node.js dependencies"
  #       run: "yarn install --immutable"

  #     - name: "Lint the contracts"
  #       run: "yarn lint"

  #     - name: "Add lint summary"
  #       run: |
  #         echo "## Lint result" >> $GITHUB_STEP_SUMMARY
  #         echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Build core
        run: |
          cd "${GITHUB_WORKSPACE}/core"
          forge build
      - name: Build periphery
        run: |
          cd "${GITHUB_WORKSPACE}/periphery"
          forge build
      - name: Summarize
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  test:
    needs: ["build"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: "Generate a fuzz seed that changes weekly to avoid burning through RPC allowance"
        run: >
          echo "FOUNDRY_FUZZ_SEED=$(
            echo $(($EPOCHSECONDS - $EPOCHSECONDS % 604800))
          )" >> $GITHUB_ENV
      - name: Test core
        run: |
          cd "${GITHUB_WORKSPACE}/core"
          forge test -vv --no-match-contract ".*Gas" --no-match-test "historical"
      - name: Test periphery
        run: |
          cd "${GITHUB_WORKSPACE}/periphery"
          forge test
      - name: Summarize
        run: |
          echo "## Tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
